export * from './authen'
export * from './compare'
export * from './detailResult'
export * from './result'
export * from './history'
export * from './home'
export * from './search'
export * from './profile'
